### ISSUE TITLE
Spawner + Seeds

### ISSUE THREAD

**Issue by JimKnoxx** [Anon10W1z/CraftPlusPlus#2]
Spawner always drop as Pig Spawner.

Carrots and Potatoes do not plant them self. Maybe also add Saplings to the auto-plant mode.

**Comment by Anon10W1z** [comment]
I will look into this.

**Comment by Anon10W1z** [comment]
The mob spawner issue was unreproducable. The carrots and potatoes issue has been fixed with commit e40f66008dbb6d326968ae6c31ca638a64df9dd9
