### ISSUE TITLE
1.8 3.7.2 crashing server hard during game play

### ISSUE THREAD

**Issue by kreezxil** [Anon10W1z/CraftPlusPlus#4]
Issue: craft++ crashing and hanging server hard during gameplay, using forge build 1504

crash report:
https://gist.github.com/23a8fa28a386b8615bb9

fml server latest:
https://gist.github.com/f28a06e46128e2b1e0d6

**Comment by Anon10W1z** [comment]
This is an issue with vanilla and there is nothing I can do about it. This shouldn't happen regardless. Tell me if it manifests itself again.

**Comment by kreezxil** [comment]
I'll revisit your mod on your next version.
