### ISSUE TITLE
Question about upgrading from 2.3.3 to your latest 3.7.3

### ISSUE THREAD

**Issue by chezpaul** [Anon10W1z/CraftPlusPlus#5]
I'm running a KCauldron 1492.162 server with Craft.-2.3.3 on it. When I take it out, the server won't even start, if I upgrade it with 3.7.3, the server won't boot either. I was wondering if you had an insight into this? I also tried to replace the inside of the jar file with the newer ones, keeping the same 2.3.3 name but that didn't work either.

Any thoughts?

**Comment by chezpaul** [comment]
I guess I'm the only one here...

**Comment by Anon10W1z** [comment]
I'd need the server log.

**Comment by chezpaul** [comment]
There is none, it crashes right away. Bam!  ;-)
Server won't even start.
Same as if I take the mod out. Server won't start anymore. Put it back in and it's fine.
Very weird.

**Comment by Anon10W1z** [comment]
Very weird indeed. I'll have to test this myself. Have you tried 3.8?

**Comment by chezpaul** [comment]
No I didn't yet. I'll try it Tuesday when the kids are done playing on the server.  ;-)
Thanks

**Comment by chezpaul** [comment]
Where can I find 3.8?

**Comment by Anon10W1z** [comment]
https://github.com/Anon10W1z/CraftPlusPlus/releases/download/3.8/CraftPlusPlus-3.8.jar

**Comment by chezpaul** [comment]
This is crazy.. if I take out craft.-2.3.3.jar then my server won't even boot. AT ALL!!!

I get this:
Last login: Mon Feb 15 10:34:52 on ttys000
Bwayserver:~ bwayxxx$ /Users/bwayxxx/Desktop/KCauldron/start_server.command ; exit;
A problem occurred running the Server launcher.logout

[Process completed]

I put it back in and it boots.
How amazing is that?
What did you put in this file ?  ;-)
Would you be interested in checking it out ? Do you already have it ?

**Comment by chezpaul** [comment]
This is my boot script... in case...

#!/bin/bash
cd "$( dirname "$0" )"
java -Xms8G -Xmx8G -XX:NewRatio=3 -XX:SurvivorRatio=3 -XX:TargetSurvivorRatio=80 -XX:MaxTenuringThreshold=8 -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:MaxGCPauseMillis=10 -XX:GCPauseIntervalMillis=50 -XX:+ExplicitGCInvokesConcurrent -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=60 -XX:+BindGCTaskThreadsToCPUs -Xnoclassgc -jar kcauldron_server.jar -o true
